#' @title  Run PARADIGM on multi-omic data
#'
#' @param real_se  A SummarizedExperiment object of PARADIGM CNA and RNA states.
#'                 It is the same matrix as the output from `ppRealInp()`.
#'
#' @param fpth  Name of a pathway file for PARADIGM.
#'
#' @param outdir  Output folder to save all results.
#'
#' @param PARADIGM_bin  PARADIGM binary, which can be downloaded from 
#' https://github.com/sng87/paradigm-scripts/tree/master/public/exe. Note that
#' the binary is only available for Linux or MacOS. Default: NULL
#'
#' @param nohup_bin  nohup binary, which is used for long running PARADIGM jobs.
#'                   Default: NULL
#'
#' @param sampleids  A vector of sample IDs to run PARADIGM on. If not provided,
#'                   all the samples that exist in both copy-number alteration
#'                   and RNA files will be ran. Default: NULL
#'
#' @inheritParams ppRnaInp
#'
#' @usage runPrd(real_se, fpth, outdir, PARADIGM_bin=NULL, nohup_bin=NULL,
#'     sampleids=NULL, threads=1)
#'
#' @return None
#'
#' @export
#'
#' @examples
#'
#' freal = system.file('extdata/TcgaInp/inp_real.rds', package='MPAC')
#' real_se  = readRDS(freal)
#'
#' fpth = system.file('extdata/Pth/tiny_pth.txt', package='MPAC')
#' outdir = tempdir()
#' paradigm_bin = '/path/to/PARADIGM'  ## change to binary location
#'
#' # depends on external PARADIGM binary, do not run
#' runPrd(real_se, fpth, outdir, paradigm_bin, sampleids=c('TCGA-CF-7100'))
#'
#' @importFrom BiocParallel bplapply
#' @importFrom SummarizedExperiment assays
#'
runPrd <- function(real_se, fpth, outdir, PARADIGM_bin=NULL,
    nohup_bin=NULL, sampleids=NULL, threads=1) {

    prots = rownames(real_se) |> sort()
    cn_state_mat  <- assays(real_se)$CN_state  |> _[prots, ] |> t() 
    rna_state_mat <- assays(real_se)$RNA_state |> _[prots, ] |> t()

    # jntl <- findJntPatProt(cn_state_mat, rna_state_mat, fpth, sampleids)
    if ( ! file.exists(outdir)) dir.create(outdir, recursive=TRUE)

    pats = rownames(cn_state_mat)
    dummy <- bplapply(pats, runPrdByPat, cn_state_mat, rna_state_mat, fpth, 
        outdir, PARADIGM_bin, nohup_bin, BPPARAM=getBPPARAM(threads))

    # lapply(pats, runPrdByPat, cn_state_mat, rna_state_mat, fpth, 
    #     outdir, PARADIGM_bin, nohup_bin)
}

#' @title  Run PARADIGM on permuted data
#'
#' @param perml  A list of SummarizedExperiment objects of permuted CNA and 
#'               RNA states generated by `ppPermInp()`.
#'
#' @inheritParams runPrd
#'
#' @usage runPermPrd(perml, fpth, outdir,
#'     PARADIGM_bin=NULL, nohup_bin=NULL, sampleids=NULL, threads=1)
#'
#' @return None
#'
#' @export
#'
#' @examples
#'
#' fperm = system.file('extdata/TcgaInp/inp_perm.rds', package='MPAC')
#' perml = readRDS(fperm)
#' fpth = system.file('extdata/Pth/tiny_pth.txt', package='MPAC')
#' outdir = tempdir()
#' paradigm_bin = '/path/to/PARADIGM'  ## change to binary location
#' pat = 'TCGA-CV-7100'
#'
#' # depends on external PARADIGM binary, do not run
#' runPermPrd(perml, fpth, outdir, paradigm_bin, sampleids=c(pat))
#'
#' @importFrom BiocParallel bplapply
#' @importFrom S4Vectors metadata
#'
runPermPrd <- function(perml, fpth, outdir, PARADIGM_bin=NULL, nohup_bin=NULL,
    sampleids=NULL, threads=1) {

    dummy <- lapply(perml, function(perm_se) {
        iperm_tag <- paste0('p', metadata(perm_se)$i)
        iperm_outdir <- paste0(outdir, '/', iperm_tag, '/')
        runPrd(perm_se, fpth, iperm_outdir, PARADIGM_bin, nohup_bin, sampleids, 
            threads)
    })
}


#findJntPatProt <- function(cn_state_mat, rna_state_mat, fpth, sampleids) {
#   in_cnmat  <- t(cn_state_mat)
#   in_rnamat <- t(rna_state_mat)

#   lines <- readLines(fpth)
#   pth_prots <- lines[grepl("^protein\t", lines, perl=TRUE)] |>
#               tstrsplit("\t") |> _[[2]]

#   pats <- intersect(rownames(in_cnmat), rownames(in_rnamat)) |>
#           intersect(sampleids) |> sort()

#   prots <- intersect(colnames(in_cnmat), colnames(in_rnamat)) |>
#           intersect(pth_prots) |> sort()

#   cnmat  <- in_cnmat[ pats, prots, drop=FALSE]
#   rnamat <- in_rnamat[pats, prots, drop=FALSE]

#   list(pats=pats, cn=cnmat, rna=rnamat)
#}

runPrdByPat <- function(pat, cnmat, rnamat, fpth, outdir, PARADIGM_bin,
    nohup_bin) {

    fone_samp <- tag <- NULL
    out_prefix <- paste0(outdir, '/', pat, '_')
    omicdt <- data.table( rbind(
        c( 'genome', 'inp_focal'       ),
        c( 'mRNA',   'inp_log10fpkmP1' )
    )) |> setnames( c('type', 'tag') ) |>
    _[, fone_samp := paste0(out_prefix, tag, '.tsv')]

    type2mat <- list( 
        'genome' = cnmat[ pat, , drop=FALSE], 
        'mRNA'   = rnamat[pat, , drop=FALSE] 
    )

    fcfg <- paste0(out_prefix, 'cfg.txt')
    fcpt <- paste0(out_prefix, 'cpt.txt')
    fipl <- paste0(out_prefix, 'ipl.txt')

    Map(prepOmic, omicdt$type, omicdt$fone_samp, MoreArgs=list(type2mat))

    prepConfig(fcfg, omicdt)

    runPARADIGM(fcfg, fcpt, fipl, out_prefix, fpth, PARADIGM_bin, nohup_bin)
}

prepOmic <- function(type, fone_samp, type2mat) {
    type2mat[[type]] |>
    as.data.table(keep.rownames=TRUE) |> setnames('rn', 'pat') |>
    fwrite(fone_samp, quote=FALSE, sep="\t")
}

runPARADIGM <- function(fcfg, fcpt, fipl, out_prefix, fpth, PARADIGM_bin, 
    nohup_bin){
    
    args <- c( 
        '-p', fpth,
        '-c', fcfg, 
        '-b', dirname(out_prefix) |> paste0('/'),
        '-e', fcpt,
        '-o', fipl,
        '-m 1'  ## max_mem_in_G
    )
    
    fout <- paste0(out_prefix, 'run.out')
    ferr <- paste0(out_prefix, 'run.err')

    if ( is.null(PARADIGM_bin) ) {
        paste0("Please provide PARADIGM binary. See vignette for details\n")
    } else {
        ## cat(PARADIGM_bin, args, "\n")
        if ( is.null(nohup_bin) ) {
            system2(PARADIGM_bin, args=args, stdout=fout, stderr=ferr)
        } else {
            args <- c(PARADIGM_bin, args)
            system2(nohup_bin, args=args, stdout=fout, stderr=ferr)
        }
    }
}

prepConfig <- function(fcfg, omicdt) {
    s_obss <- c()
    s_evis <- c()
    options(scipen=10) ## for cnv_cutoff == 0.0001
    for ( i in seq_len(nrow(omicdt)) ) {
        fname_one_samp <- basename(omicdt[i]$fone_samp)
        s_obss <- c(s_obss, paste0(fname_one_samp, '=-obs>'))
        s_evis <- c(s_evis, paste0('evidence [suffix=', fname_one_samp,
            ',node=', omicdt[i]$type, ',disc=-0.5;0.5',
            ',epsilon=0.001,epsilon0=0.2]'))
    }

    paste0( 
        "pathway [max_in_degree=5]\n",
        "inference [method=BP,updates=SEQFIX,tol=1e-9,maxiter=10000,",
            "logdomain=0]\n",
        'em_step [', paste(s_obss, collapse=','), "]\n",
        "em [max_iters=10000,log_z_tol=1e-10]\n",
        paste(s_evis, collapse="\n") ) |>
    write(file=fcfg)
}
